{{- if .Values.ambient.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dapr-ambient.serviceAccountName" . }}
  labels:
    {{- include "dapr-ambient.labels" . | nindent 4 }}
  {{- with .Values.ambient.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
